// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAlarm(arg1) {
  return window['go']['main']['App']['CreateAlarm'](arg1);
}

export function DeleteAlarm(arg1) {
  return window['go']['main']['App']['DeleteAlarm'](arg1);
}

export function DeleteLocation(arg1) {
  return window['go']['main']['App']['DeleteLocation'](arg1);
}

export function FormatTime(arg1, arg2) {
  return window['go']['main']['App']['FormatTime'](arg1, arg2);
}

export function GetAlarms() {
  return window['go']['main']['App']['GetAlarms']();
}

export function GetCalculationMethods() {
  return window['go']['main']['App']['GetCalculationMethods']();
}

export function GetCurrentDate() {
  return window['go']['main']['App']['GetCurrentDate']();
}

export function GetCurrentLocation() {
  return window['go']['main']['App']['GetCurrentLocation']();
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetDistanceToMakkah() {
  return window['go']['main']['App']['GetDistanceToMakkah']();
}

export function GetNextPrayer() {
  return window['go']['main']['App']['GetNextPrayer']();
}

export function GetPrayerTimes(arg1) {
  return window['go']['main']['App']['GetPrayerTimes'](arg1);
}

export function GetQiblaDirection() {
  return window['go']['main']['App']['GetQiblaDirection']();
}

export function GetSavedLocations() {
  return window['go']['main']['App']['GetSavedLocations']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTodayPrayerTimes() {
  return window['go']['main']['App']['GetTodayPrayerTimes']();
}

export function ParseFloat(arg1) {
  return window['go']['main']['App']['ParseFloat'](arg1);
}

export function ResetSettingsToDefaults() {
  return window['go']['main']['App']['ResetSettingsToDefaults']();
}

export function SaveLocation(arg1) {
  return window['go']['main']['App']['SaveLocation'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchLocations(arg1) {
  return window['go']['main']['App']['SearchLocations'](arg1);
}

export function SetCurrentLocation(arg1) {
  return window['go']['main']['App']['SetCurrentLocation'](arg1);
}

export function ToggleAlarm(arg1, arg2) {
  return window['go']['main']['App']['ToggleAlarm'](arg1, arg2);
}

export function UpdateAlarm(arg1) {
  return window['go']['main']['App']['UpdateAlarm'](arg1);
}
