// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateAlarm(arg1:models.Alarm):Promise<models.Alarm>;

export function DeleteAlarm(arg1:number):Promise<void>;

export function DeleteLocation(arg1:number):Promise<void>;

export function FormatTime(arg1:string,arg2:boolean):Promise<string>;

export function GetAlarms():Promise<Array<models.Alarm>>;

export function GetCalculationMethods():Promise<Array<Record<string, string>>>;

export function GetCurrentDate():Promise<string>;

export function GetCurrentLocation():Promise<models.Location>;

export function GetCurrentTime():Promise<string>;

export function GetDistanceToMakkah():Promise<number>;

export function GetNextPrayer():Promise<Record<string, any>>;

export function GetPrayerTimes(arg1:string):Promise<models.PrayerTimes>;

export function GetQiblaDirection():Promise<number>;

export function GetSavedLocations():Promise<Array<models.Location>>;

export function GetSettings():Promise<models.AppSettings>;

export function GetTodayPrayerTimes():Promise<models.PrayerTimes>;

export function ParseFloat(arg1:string):Promise<number>;

export function ResetSettingsToDefaults():Promise<void>;

export function SaveLocation(arg1:models.Location):Promise<void>;

export function SaveSettings(arg1:models.AppSettings):Promise<void>;

export function SearchLocations(arg1:string):Promise<Array<models.Location>>;

export function SetCurrentLocation(arg1:models.Location):Promise<void>;

export function ToggleAlarm(arg1:number,arg2:boolean):Promise<void>;

export function UpdateAlarm(arg1:models.Alarm):Promise<void>;
